spring.application.name=E-Library
server.port=8080

app.download.path=/tmp/zip/

# Supabase configuration
PROJECT_URL=https://gdfpedgcdxonyzmfhtll.supabase.co
SECRET_KEY=sb_secret_J9lTLzpFJ0X7P-o4H6qKvg_iui_4Tsy
DB_PASSWORD=edge2025masters
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



logging.file.name=logs/e-library.log


# logging.file.max-size=10MB
# logging.file.max-history=7


#logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} [user:%X{userId:-N/A}, roles:%X{userRoles:-N/A}] - %msg%n
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [user:%X{userId:-N/A}, roles:%X{userRoles:-N/A}] - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} [%15.15thread] %-5level %-40.40logger{39} [traceId:%X{traceId:-}] [user:%X{userId:-N/A}, roles:%X{userRoles:-N/A}] : %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%15.15thread] %-5level %-40.40logger{39} [traceId:%X{traceId:-}] [user:%X{userId:-N/A}, roles:%X{userRoles:-N/A}] : %msg%n


# Actuator Configuration
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always

# Metrics Configuration
management.metrics.tags.application=e-library
management.metrics.enable.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99

# Additional metrics settings
management.metrics.distribution.slo.http.server.requests=100ms,500ms,1s

# Custom metric prefixes
management.prometheus.metrics.export.step=30s
management.prometheus.metrics.export.descriptions=true